"""initial migration

Revision ID: 4f08de9202b6
Revises: 
Create Date: 2026-07-14 21:41:33.277333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f08de9202b6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('threats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('indicator', sa.String(length=512), nullable=False),
    sa.Column('indicator_type', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('indicator', 'source', name='uq_threat_indicator_source')
    )
    with op.batch_alter_table('threats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_threats_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_threats_country'), ['country'], unique=False)
        batch_op.create_index(batch_op.f('ix_threats_indicator'), ['indicator'], unique=False)
        batch_op.create_index(batch_op.f('ix_threats_indicator_type'), ['indicator_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_threats_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_threats_source'), ['source'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('subscription', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('threats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_threats_source'))
        batch_op.drop_index(batch_op.f('ix_threats_severity'))
        batch_op.drop_index(batch_op.f('ix_threats_indicator_type'))
        batch_op.drop_index(batch_op.f('ix_threats_indicator'))
        batch_op.drop_index(batch_op.f('ix_threats_country'))
        batch_op.drop_index(batch_op.f('ix_threats_category'))

    op.drop_table('threats')
    # ### end Alembic commands ###
